# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LiftInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, lift_description: str=None, lift_ipv6_id: str=None, lift_start_time: str=None, lift_start_time_unix: str=None, location_id: str=None, lift_fuel_level: float=None, lift_fuel_type: str=None, lift_fork_position: float=None, lift_direction: str=None, lift_vibration_hz: float=None, lift_velocity: float=None, lift_engine_temp_c: float=None, lift_engine_temp_f: float=None, lift_engine_temp_k: float=None, lift_engine_temp_r: float=None, lift_latitude: float=None, lift_longitude: float=None, lift_weight: float=None, lift_class: str=None):  # noqa: E501
        """LiftInfo - a model defined in Swagger

        :param code: The code of this LiftInfo.  # noqa: E501
        :type code: int
        :param lift_description: The lift_description of this LiftInfo.  # noqa: E501
        :type lift_description: str
        :param lift_ipv6_id: The lift_ipv6_id of this LiftInfo.  # noqa: E501
        :type lift_ipv6_id: str
        :param lift_start_time: The lift_start_time of this LiftInfo.  # noqa: E501
        :type lift_start_time: str
        :param lift_start_time_unix: The lift_start_time_unix of this LiftInfo.  # noqa: E501
        :type lift_start_time_unix: str
        :param location_id: The location_id of this LiftInfo.  # noqa: E501
        :type location_id: str
        :param lift_fuel_level: The lift_fuel_level of this LiftInfo.  # noqa: E501
        :type lift_fuel_level: float
        :param lift_fuel_type: The lift_fuel_type of this LiftInfo.  # noqa: E501
        :type lift_fuel_type: str
        :param lift_fork_position: The lift_fork_position of this LiftInfo.  # noqa: E501
        :type lift_fork_position: float
        :param lift_direction: The lift_direction of this LiftInfo.  # noqa: E501
        :type lift_direction: str
        :param lift_vibration_hz: The lift_vibration_hz of this LiftInfo.  # noqa: E501
        :type lift_vibration_hz: float
        :param lift_velocity: The lift_velocity of this LiftInfo.  # noqa: E501
        :type lift_velocity: float
        :param lift_engine_temp_c: The lift_engine_temp_c of this LiftInfo.  # noqa: E501
        :type lift_engine_temp_c: float
        :param lift_engine_temp_f: The lift_engine_temp_f of this LiftInfo.  # noqa: E501
        :type lift_engine_temp_f: float
        :param lift_engine_temp_k: The lift_engine_temp_k of this LiftInfo.  # noqa: E501
        :type lift_engine_temp_k: float
        :param lift_engine_temp_r: The lift_engine_temp_r of this LiftInfo.  # noqa: E501
        :type lift_engine_temp_r: float
        :param lift_latitude: The lift_latitude of this LiftInfo.  # noqa: E501
        :type lift_latitude: float
        :param lift_longitude: The lift_longitude of this LiftInfo.  # noqa: E501
        :type lift_longitude: float
        :param lift_weight: The lift_weight of this LiftInfo.  # noqa: E501
        :type lift_weight: float
        :param lift_class: The lift_class of this LiftInfo.  # noqa: E501
        :type lift_class: str
        """
        self.swagger_types = {
            'code': int,
            'lift_description': str,
            'lift_ipv6_id': str,
            'lift_start_time': str,
            'lift_start_time_unix': str,
            'location_id': str,
            'lift_fuel_level': float,
            'lift_fuel_type': str,
            'lift_fork_position': float,
            'lift_direction': str,
            'lift_vibration_hz': float,
            'lift_velocity': float,
            'lift_engine_temp_c': float,
            'lift_engine_temp_f': float,
            'lift_engine_temp_k': float,
            'lift_engine_temp_r': float,
            'lift_latitude': float,
            'lift_longitude': float,
            'lift_weight': float,
            'lift_class': str
        }

        self.attribute_map = {
            'code': 'code',
            'lift_description': 'LiftDescription',
            'lift_ipv6_id': 'LiftIPV6Id',
            'lift_start_time': 'LiftStartTime',
            'lift_start_time_unix': 'LiftStartTimeUnix',
            'location_id': 'LocationId',
            'lift_fuel_level': 'LiftFuelLevel',
            'lift_fuel_type': 'LiftFuelType',
            'lift_fork_position': 'LiftForkPosition',
            'lift_direction': 'LiftDirection',
            'lift_vibration_hz': 'LiftVibrationHz',
            'lift_velocity': 'LiftVelocity',
            'lift_engine_temp_c': 'LiftEngineTempC',
            'lift_engine_temp_f': 'LiftEngineTempF',
            'lift_engine_temp_k': 'LiftEngineTempK',
            'lift_engine_temp_r': 'LiftEngineTempR',
            'lift_latitude': 'LiftLatitude',
            'lift_longitude': 'LiftLongitude',
            'lift_weight': 'LiftWeight',
            'lift_class': 'LiftClass'
        }

        self._code = code
        self._lift_description = lift_description
        self._lift_ipv6_id = lift_ipv6_id
        self._lift_start_time = lift_start_time
        self._lift_start_time_unix = lift_start_time_unix
        self._location_id = location_id
        self._lift_fuel_level = lift_fuel_level
        self._lift_fuel_type = lift_fuel_type
        self._lift_fork_position = lift_fork_position
        self._lift_direction = lift_direction
        self._lift_vibration_hz = lift_vibration_hz
        self._lift_velocity = lift_velocity
        self._lift_engine_temp_c = lift_engine_temp_c
        self._lift_engine_temp_f = lift_engine_temp_f
        self._lift_engine_temp_k = lift_engine_temp_k
        self._lift_engine_temp_r = lift_engine_temp_r
        self._lift_latitude = lift_latitude
        self._lift_longitude = lift_longitude
        self._lift_weight = lift_weight
        self._lift_class = lift_class

    @classmethod
    def from_dict(cls, dikt) -> 'LiftInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LiftInfo of this LiftInfo.  # noqa: E501
        :rtype: LiftInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this LiftInfo.


        :return: The code of this LiftInfo.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this LiftInfo.


        :param code: The code of this LiftInfo.
        :type code: int
        """

        self._code = code

    @property
    def lift_description(self) -> str:
        """Gets the lift_description of this LiftInfo.


        :return: The lift_description of this LiftInfo.
        :rtype: str
        """
        return self._lift_description

    @lift_description.setter
    def lift_description(self, lift_description: str):
        """Sets the lift_description of this LiftInfo.


        :param lift_description: The lift_description of this LiftInfo.
        :type lift_description: str
        """

        self._lift_description = lift_description

    @property
    def lift_ipv6_id(self) -> str:
        """Gets the lift_ipv6_id of this LiftInfo.


        :return: The lift_ipv6_id of this LiftInfo.
        :rtype: str
        """
        return self._lift_ipv6_id

    @lift_ipv6_id.setter
    def lift_ipv6_id(self, lift_ipv6_id: str):
        """Sets the lift_ipv6_id of this LiftInfo.


        :param lift_ipv6_id: The lift_ipv6_id of this LiftInfo.
        :type lift_ipv6_id: str
        """

        self._lift_ipv6_id = lift_ipv6_id

    @property
    def lift_start_time(self) -> str:
        """Gets the lift_start_time of this LiftInfo.


        :return: The lift_start_time of this LiftInfo.
        :rtype: str
        """
        return self._lift_start_time

    @lift_start_time.setter
    def lift_start_time(self, lift_start_time: str):
        """Sets the lift_start_time of this LiftInfo.


        :param lift_start_time: The lift_start_time of this LiftInfo.
        :type lift_start_time: str
        """

        self._lift_start_time = lift_start_time

    @property
    def lift_start_time_unix(self) -> str:
        """Gets the lift_start_time_unix of this LiftInfo.


        :return: The lift_start_time_unix of this LiftInfo.
        :rtype: str
        """
        return self._lift_start_time_unix

    @lift_start_time_unix.setter
    def lift_start_time_unix(self, lift_start_time_unix: str):
        """Sets the lift_start_time_unix of this LiftInfo.


        :param lift_start_time_unix: The lift_start_time_unix of this LiftInfo.
        :type lift_start_time_unix: str
        """

        self._lift_start_time_unix = lift_start_time_unix

    @property
    def location_id(self) -> str:
        """Gets the location_id of this LiftInfo.


        :return: The location_id of this LiftInfo.
        :rtype: str
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id: str):
        """Sets the location_id of this LiftInfo.


        :param location_id: The location_id of this LiftInfo.
        :type location_id: str
        """

        self._location_id = location_id

    @property
    def lift_fuel_level(self) -> float:
        """Gets the lift_fuel_level of this LiftInfo.


        :return: The lift_fuel_level of this LiftInfo.
        :rtype: float
        """
        return self._lift_fuel_level

    @lift_fuel_level.setter
    def lift_fuel_level(self, lift_fuel_level: float):
        """Sets the lift_fuel_level of this LiftInfo.


        :param lift_fuel_level: The lift_fuel_level of this LiftInfo.
        :type lift_fuel_level: float
        """

        self._lift_fuel_level = lift_fuel_level

    @property
    def lift_fuel_type(self) -> str:
        """Gets the lift_fuel_type of this LiftInfo.


        :return: The lift_fuel_type of this LiftInfo.
        :rtype: str
        """
        return self._lift_fuel_type

    @lift_fuel_type.setter
    def lift_fuel_type(self, lift_fuel_type: str):
        """Sets the lift_fuel_type of this LiftInfo.


        :param lift_fuel_type: The lift_fuel_type of this LiftInfo.
        :type lift_fuel_type: str
        """

        self._lift_fuel_type = lift_fuel_type

    @property
    def lift_fork_position(self) -> float:
        """Gets the lift_fork_position of this LiftInfo.


        :return: The lift_fork_position of this LiftInfo.
        :rtype: float
        """
        return self._lift_fork_position

    @lift_fork_position.setter
    def lift_fork_position(self, lift_fork_position: float):
        """Sets the lift_fork_position of this LiftInfo.


        :param lift_fork_position: The lift_fork_position of this LiftInfo.
        :type lift_fork_position: float
        """

        self._lift_fork_position = lift_fork_position

    @property
    def lift_direction(self) -> str:
        """Gets the lift_direction of this LiftInfo.


        :return: The lift_direction of this LiftInfo.
        :rtype: str
        """
        return self._lift_direction

    @lift_direction.setter
    def lift_direction(self, lift_direction: str):
        """Sets the lift_direction of this LiftInfo.


        :param lift_direction: The lift_direction of this LiftInfo.
        :type lift_direction: str
        """

        self._lift_direction = lift_direction

    @property
    def lift_vibration_hz(self) -> float:
        """Gets the lift_vibration_hz of this LiftInfo.


        :return: The lift_vibration_hz of this LiftInfo.
        :rtype: float
        """
        return self._lift_vibration_hz

    @lift_vibration_hz.setter
    def lift_vibration_hz(self, lift_vibration_hz: float):
        """Sets the lift_vibration_hz of this LiftInfo.


        :param lift_vibration_hz: The lift_vibration_hz of this LiftInfo.
        :type lift_vibration_hz: float
        """

        self._lift_vibration_hz = lift_vibration_hz

    @property
    def lift_velocity(self) -> float:
        """Gets the lift_velocity of this LiftInfo.


        :return: The lift_velocity of this LiftInfo.
        :rtype: float
        """
        return self._lift_velocity

    @lift_velocity.setter
    def lift_velocity(self, lift_velocity: float):
        """Sets the lift_velocity of this LiftInfo.


        :param lift_velocity: The lift_velocity of this LiftInfo.
        :type lift_velocity: float
        """

        self._lift_velocity = lift_velocity

    @property
    def lift_engine_temp_c(self) -> float:
        """Gets the lift_engine_temp_c of this LiftInfo.


        :return: The lift_engine_temp_c of this LiftInfo.
        :rtype: float
        """
        return self._lift_engine_temp_c

    @lift_engine_temp_c.setter
    def lift_engine_temp_c(self, lift_engine_temp_c: float):
        """Sets the lift_engine_temp_c of this LiftInfo.


        :param lift_engine_temp_c: The lift_engine_temp_c of this LiftInfo.
        :type lift_engine_temp_c: float
        """

        self._lift_engine_temp_c = lift_engine_temp_c

    @property
    def lift_engine_temp_f(self) -> float:
        """Gets the lift_engine_temp_f of this LiftInfo.


        :return: The lift_engine_temp_f of this LiftInfo.
        :rtype: float
        """
        return self._lift_engine_temp_f

    @lift_engine_temp_f.setter
    def lift_engine_temp_f(self, lift_engine_temp_f: float):
        """Sets the lift_engine_temp_f of this LiftInfo.


        :param lift_engine_temp_f: The lift_engine_temp_f of this LiftInfo.
        :type lift_engine_temp_f: float
        """

        self._lift_engine_temp_f = lift_engine_temp_f

    @property
    def lift_engine_temp_k(self) -> float:
        """Gets the lift_engine_temp_k of this LiftInfo.


        :return: The lift_engine_temp_k of this LiftInfo.
        :rtype: float
        """
        return self._lift_engine_temp_k

    @lift_engine_temp_k.setter
    def lift_engine_temp_k(self, lift_engine_temp_k: float):
        """Sets the lift_engine_temp_k of this LiftInfo.


        :param lift_engine_temp_k: The lift_engine_temp_k of this LiftInfo.
        :type lift_engine_temp_k: float
        """

        self._lift_engine_temp_k = lift_engine_temp_k

    @property
    def lift_engine_temp_r(self) -> float:
        """Gets the lift_engine_temp_r of this LiftInfo.


        :return: The lift_engine_temp_r of this LiftInfo.
        :rtype: float
        """
        return self._lift_engine_temp_r

    @lift_engine_temp_r.setter
    def lift_engine_temp_r(self, lift_engine_temp_r: float):
        """Sets the lift_engine_temp_r of this LiftInfo.


        :param lift_engine_temp_r: The lift_engine_temp_r of this LiftInfo.
        :type lift_engine_temp_r: float
        """

        self._lift_engine_temp_r = lift_engine_temp_r

    @property
    def lift_latitude(self) -> float:
        """Gets the lift_latitude of this LiftInfo.


        :return: The lift_latitude of this LiftInfo.
        :rtype: float
        """
        return self._lift_latitude

    @lift_latitude.setter
    def lift_latitude(self, lift_latitude: float):
        """Sets the lift_latitude of this LiftInfo.


        :param lift_latitude: The lift_latitude of this LiftInfo.
        :type lift_latitude: float
        """

        self._lift_latitude = lift_latitude

    @property
    def lift_longitude(self) -> float:
        """Gets the lift_longitude of this LiftInfo.


        :return: The lift_longitude of this LiftInfo.
        :rtype: float
        """
        return self._lift_longitude

    @lift_longitude.setter
    def lift_longitude(self, lift_longitude: float):
        """Sets the lift_longitude of this LiftInfo.


        :param lift_longitude: The lift_longitude of this LiftInfo.
        :type lift_longitude: float
        """

        self._lift_longitude = lift_longitude

    @property
    def lift_weight(self) -> float:
        """Gets the lift_weight of this LiftInfo.


        :return: The lift_weight of this LiftInfo.
        :rtype: float
        """
        return self._lift_weight

    @lift_weight.setter
    def lift_weight(self, lift_weight: float):
        """Sets the lift_weight of this LiftInfo.


        :param lift_weight: The lift_weight of this LiftInfo.
        :type lift_weight: float
        """

        self._lift_weight = lift_weight

    @property
    def lift_class(self) -> str:
        """Gets the lift_class of this LiftInfo.


        :return: The lift_class of this LiftInfo.
        :rtype: str
        """
        return self._lift_class

    @lift_class.setter
    def lift_class(self, lift_class: str):
        """Sets the lift_class of this LiftInfo.


        :param lift_class: The lift_class of this LiftInfo.
        :type lift_class: str
        """

        self._lift_class = lift_class
